# Generated by Django 5.2.5 on 2025-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('IdRol', models.IntegerField(primary_key=True, serialize=False)),
                ('NameRol', models.TextField()),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
    ]
