# Generated by Django 5.2.5 on 2025-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='IdRol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
