# Generated by Django 5.2.5 on 2025-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('IdCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('NameCliente', models.TextField()),
                ('EmailCliente', models.TextField()),
                ('PhoneCliente', models.TextField()),
                ('RoleCliente', models.TextField()),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
    ]
