# Generated by Django 5.2.5 on 2025-08-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='IdCliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
