# Generated by Django 5.2.5 on 2025-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_producto_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='IdProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
