# Generated by Django 5.2.5 on 2025-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('IdServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('NameServicio', models.TextField()),
                ('DescriptionServicio', models.TextField()),
                ('PriceServicio', models.FloatField()),
            ],
            options={
                'db_table': 'Servicios',
            },
        ),
    ]
